### ISSUE TITLE
Built sample and getting NullPointerException at 'void com.github.pedrovgs.nox.NoxItemCatalog.addObserver(java.util.Observer)'

### ISSUE THREAD

**Issue by trinizz84** [pedrovgs/Nox#8]
07-28 18:43:14.499 26104 26104 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.pedrovgs.nox.NoxItemCatalog.addObserver(java.util.Observer)' on a null object reference
07-28 18:43:14.499 26104 26104 E AndroidRuntime:        at com.github.pedrovgs.nox.NoxView.resume(NoxView.java:267)
07-28 18:43:14.499 26104 26104 E AndroidRuntime:        at com.github.pedrovgs.nox.NoxView.onVisibilityChanged(NoxView.java:239)

**Comment by trinizz84** [comment]
Does not happen on 4.4 device. Have no texted on any 5.* devices but 6.0.1 is where it consistently occurs.

**Comment by pedrovgs** [comment]
Hi @trinizz84 do you have the steps to reproduce the bug? I could fix it with a null check, but I'd like to know if you are doing something special to reproduce the crash. Thanks!
